### ISSUE TITLE
Renaming Files

### ISSUE THREAD

**Issue by Kerl1310** [wcrasta/SWA-Scraper#16]
Currently a bunch of the files are named in a way that isn't really descriptive. These should be updated to improve readability.

**Comment by wcrasta** [comment]
Kyle,

I have closed this issue as well as the other issues/enhancements that you have submitted. I appreciate your enthusiasm for this project, but I think things like these are nice to have, but not required by any means. As such, if you'd like to fix it, go ahead and I'll merge the PR; I just don't think it necessitates an issue.

I've also closed the issues with links to airline websites as I think those are pretty easy to find on the web.
