### ISSUE TITLE
Add POINTS support?

### ISSUE THREAD

**Issue by jgoggan** [wcrasta/SWA-Scraper#34]
Any chance you could modify this to work with points?  I noticed there is a line to specify USD or POINTS for the URL -- but switching over to POINTS causes it to not work.  (Code further down appears to assume dollars, of course.)

It would be great to be able to monitor points drops with this.  Thanks!

**Comment by wcrasta** [comment]
Doesn't seem like it would be too big an effort. If I'm free this weekend or next, I'll write up the implementation or get back to you if it does turn out to be a large effort. Thanks for your interest in the project!

**Comment by wcrasta** [comment]
I'm closing this enhancement request on the basis that I don't see many people asking to monitor by points. Although the concept of adding points support is simple, I don't want to refactor significant parts of the code to support both points/dollars.

However, if someone was to make a PR and add points support, I'd gladly merge it in.
