### ISSUE TITLE
Specific flight?

### ISSUE THREAD

**Issue by jgoggan** [wcrasta/SWA-Scraper#35]
Related to my other request of adding points support -- it would also be great (for points or dollars) to watch a specific FLIGHT as opposed to just any flight that day or during a specific time.

Basically, if the price of a flight drops with SWA, you can fairly easily rebook to get the discount and get the difference refunded or back as a credit.  So, this tool would be great to be able to monitor a specific flight that you've already booked - so that if that specific flight drops in price, you can make a quick adjustment.

Again, thank you for your time and this great tool!

**Comment by wcrasta** [comment]
Good idea. If I understand correctly, the user passes in an additional parameter **--flight-number** and should receive a notification whenever the price for that flight goes under a certain amount that they specify. Correct?

**Comment by jgoggan** [comment]
Correct!  It would be a way to watch an existing reservation for price drops.  A LOT of people want to do that regularly, so I think it would be a very useful feature.

**Comment by wcrasta** [comment]
Hey @jgoggan, after researching this issue for a little bit, I'm deciding not to build this functionality. It seems that Southwest is firmly against tracking price drops for flights, and they've threatened companies who have done this with legal action. I'd rather not get involved with anything like that which could get me in trouble, hope you understand!
