### ISSUE TITLE
Monitoring Flights that aren't Non-Stop

### ISSUE THREAD

**Issue by sirusss** [wcrasta/SWA-Scraper#38]
Great work with putting this together!

I'm having a hard time figuring out how to monitor flights that aren't non-stop. How do we specify the "flightnum" variable for those flights?

Thanks.

**Comment by wcrasta** [comment]
Hi @sirusss, thanks for your comment, I appreciate you taking an interest in this project. Monitoring outbound flights that aren't non-stop seems to work just fine for me. Here's an example:

**Flight on Southwest website that isn't non-stop:** https://i.imgur.com/8cUIPAF.png
**Corresponding program command:** `python app.py --company Southwest --depart HOU --arrive MDW --departure-date 08/21/2018 --departure-time ANYTIME --passengers 1 --max-price 200 --interval 30 --no-text --flightnum 867 --one-way`
**Result of program:** https://i.imgur.com/I54E5B1.png

**Comment by sirusss** [comment]
Thanks for the reply, @wcrasta! How would you go about monitoring the following flight: https://imgur.com/a/PLtCeL7

As you can see, this specific flight travels on both flights 1636 and 534...so what would the program command look like? Thanks!

**Comment by wcrasta** [comment]
Just specify one of the flights as the flight num. The following command should do the job:

`python app.py --company Southwest --depart HOU --arrive MDW --departure-date 08/21/2018 --departure-time ANYTIME --passengers 1 --max-price 200 --interval 30 --no-text --flightnum 1636 --one-way`
