### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by schollz** [wcrasta/SWA-Scraper#4]
I was wondering if its possible to use some of your code. A license will quickly let me know!

Thanks!

**Comment by wcrasta** [comment]
Hi,

Great to know that you find the code helpful! I'll find and add an appropriate license when I find some time. In the meanwhile, feel free to use whatever code you want (an attribution of my name, Warren Crasta, would be nice!).

Thanks!

**Comment by wcrasta** [comment]
I've just added a MIT license. Thanks for bringing attention to this issue!
